name: Build Trigger Shiv and PyInstaller

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-pyz:
    uses: ./.github/workflows/build_pyz.yml

  build-executables:
    needs: build-pyz
    uses: ./.github/workflows/build_executable.yml
