name: Build PYZ

on:
  workflow_call:
  release:
    types: [published]
  workflow_dispatch:


permissions:
  contents: write
  
jobs:
  build-pyz:
    name: Build PYZ (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    #permissions:
    #  contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: UV Sync
        run: |
          uv venv --clear
          uv sync --extra crypro --extra build

      - name: Build PYZ
        run: uv run python build_pyz.py

      - name: Run Sanity Check
        if: matrix.os != 'windows-latest'
        run: |
          python dist/zipapp/*.pyz --version
          python dist/zipapp/*.pyz --help
          python dist/zipapp/*.pyz vault health

      - name: Run sanity check (Windows)
        shell: pwsh
        if: matrix.os == 'windows-latest'
        run: |
          $pyz = Get-ChildItem -Path dist/zipapp -Filter *.pyz | Select-Object -First 1
          python $pyz --version
          python $pyz --help
          python $pyz secret manage-vault health

      - name: Build wheel + sdist (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: uv build --wheel --sdist --out-dir dist/zipapp

      - name: Generate Checksums
        if: false
        run: |
          python - <<'EOF'
          import hashlib, glob, pathlib

          out_file = pathlib.Path("dist/zipapp/SHA256SUMS.txt")
          with out_file.open("w") as f:
              for p in sorted(glob.glob("dist/zipapp/*.pyz") + 
                              glob.glob("dist/zipapp/*.whl") + 
                              glob.glob("dist/zipapp/*.tar.gz")):
                  h = hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
                  f.write(f"{h}  {p}\n")
          print("SHA256SUMS.txt generated") #dist/zipapp/SHA256SUMS.txtt
          EOF

      - name: Generate Checksums (Linux only)
        if: false # matrix.os == 'ubuntu-latest'
        run: |
          cd dist/zipapp
          sha256sum *.pyz *.whl *.tar.gz > SHA256SUMS.txt

      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          files: |
            dist/zipapp/*.pyz
            dist/zipapp/*.whl
            dist/zipapp/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
